/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RubrikIndexRouteImport } from './routes/rubrik.index'
import { Route as RaporIndexRouteImport } from './routes/rapor.index'
import { Route as PresentasiIndexRouteImport } from './routes/presentasi.index'
import { Route as PengaturanIndexRouteImport } from './routes/pengaturan.index'
import { Route as ModulIndexRouteImport } from './routes/modul.index'
import { Route as BankSoalIndexRouteImport } from './routes/bank-soal.index'
import { Route as RubrikBaruRouteImport } from './routes/rubrik.baru'
import { Route as ModulBaruRouteImport } from './routes/modul.baru'
import { Route as ModulIdRouteImport } from './routes/modul.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RubrikIndexRoute = RubrikIndexRouteImport.update({
  id: '/rubrik/',
  path: '/rubrik/',
  getParentRoute: () => rootRouteImport,
} as any)
const RaporIndexRoute = RaporIndexRouteImport.update({
  id: '/rapor/',
  path: '/rapor/',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentasiIndexRoute = PresentasiIndexRouteImport.update({
  id: '/presentasi/',
  path: '/presentasi/',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanIndexRoute = PengaturanIndexRouteImport.update({
  id: '/pengaturan/',
  path: '/pengaturan/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulIndexRoute = ModulIndexRouteImport.update({
  id: '/modul/',
  path: '/modul/',
  getParentRoute: () => rootRouteImport,
} as any)
const BankSoalIndexRoute = BankSoalIndexRouteImport.update({
  id: '/bank-soal/',
  path: '/bank-soal/',
  getParentRoute: () => rootRouteImport,
} as any)
const RubrikBaruRoute = RubrikBaruRouteImport.update({
  id: '/rubrik/baru',
  path: '/rubrik/baru',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulBaruRoute = ModulBaruRouteImport.update({
  id: '/modul/baru',
  path: '/modul/baru',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulIdRoute = ModulIdRouteImport.update({
  id: '/modul/$id',
  path: '/modul/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modul/$id': typeof ModulIdRoute
  '/modul/baru': typeof ModulBaruRoute
  '/rubrik/baru': typeof RubrikBaruRoute
  '/bank-soal/': typeof BankSoalIndexRoute
  '/modul/': typeof ModulIndexRoute
  '/pengaturan/': typeof PengaturanIndexRoute
  '/presentasi/': typeof PresentasiIndexRoute
  '/rapor/': typeof RaporIndexRoute
  '/rubrik/': typeof RubrikIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modul/$id': typeof ModulIdRoute
  '/modul/baru': typeof ModulBaruRoute
  '/rubrik/baru': typeof RubrikBaruRoute
  '/bank-soal': typeof BankSoalIndexRoute
  '/modul': typeof ModulIndexRoute
  '/pengaturan': typeof PengaturanIndexRoute
  '/presentasi': typeof PresentasiIndexRoute
  '/rapor': typeof RaporIndexRoute
  '/rubrik': typeof RubrikIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modul/$id': typeof ModulIdRoute
  '/modul/baru': typeof ModulBaruRoute
  '/rubrik/baru': typeof RubrikBaruRoute
  '/bank-soal/': typeof BankSoalIndexRoute
  '/modul/': typeof ModulIndexRoute
  '/pengaturan/': typeof PengaturanIndexRoute
  '/presentasi/': typeof PresentasiIndexRoute
  '/rapor/': typeof RaporIndexRoute
  '/rubrik/': typeof RubrikIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/modul/$id'
    | '/modul/baru'
    | '/rubrik/baru'
    | '/bank-soal/'
    | '/modul/'
    | '/pengaturan/'
    | '/presentasi/'
    | '/rapor/'
    | '/rubrik/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/modul/$id'
    | '/modul/baru'
    | '/rubrik/baru'
    | '/bank-soal'
    | '/modul'
    | '/pengaturan'
    | '/presentasi'
    | '/rapor'
    | '/rubrik'
  id:
    | '__root__'
    | '/'
    | '/modul/$id'
    | '/modul/baru'
    | '/rubrik/baru'
    | '/bank-soal/'
    | '/modul/'
    | '/pengaturan/'
    | '/presentasi/'
    | '/rapor/'
    | '/rubrik/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModulIdRoute: typeof ModulIdRoute
  ModulBaruRoute: typeof ModulBaruRoute
  RubrikBaruRoute: typeof RubrikBaruRoute
  BankSoalIndexRoute: typeof BankSoalIndexRoute
  ModulIndexRoute: typeof ModulIndexRoute
  PengaturanIndexRoute: typeof PengaturanIndexRoute
  PresentasiIndexRoute: typeof PresentasiIndexRoute
  RaporIndexRoute: typeof RaporIndexRoute
  RubrikIndexRoute: typeof RubrikIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rubrik/': {
      id: '/rubrik/'
      path: '/rubrik'
      fullPath: '/rubrik/'
      preLoaderRoute: typeof RubrikIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapor/': {
      id: '/rapor/'
      path: '/rapor'
      fullPath: '/rapor/'
      preLoaderRoute: typeof RaporIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentasi/': {
      id: '/presentasi/'
      path: '/presentasi'
      fullPath: '/presentasi/'
      preLoaderRoute: typeof PresentasiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan/': {
      id: '/pengaturan/'
      path: '/pengaturan'
      fullPath: '/pengaturan/'
      preLoaderRoute: typeof PengaturanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modul/': {
      id: '/modul/'
      path: '/modul'
      fullPath: '/modul/'
      preLoaderRoute: typeof ModulIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-soal/': {
      id: '/bank-soal/'
      path: '/bank-soal'
      fullPath: '/bank-soal/'
      preLoaderRoute: typeof BankSoalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rubrik/baru': {
      id: '/rubrik/baru'
      path: '/rubrik/baru'
      fullPath: '/rubrik/baru'
      preLoaderRoute: typeof RubrikBaruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modul/baru': {
      id: '/modul/baru'
      path: '/modul/baru'
      fullPath: '/modul/baru'
      preLoaderRoute: typeof ModulBaruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modul/$id': {
      id: '/modul/$id'
      path: '/modul/$id'
      fullPath: '/modul/$id'
      preLoaderRoute: typeof ModulIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModulIdRoute: ModulIdRoute,
  ModulBaruRoute: ModulBaruRoute,
  RubrikBaruRoute: RubrikBaruRoute,
  BankSoalIndexRoute: BankSoalIndexRoute,
  ModulIndexRoute: ModulIndexRoute,
  PengaturanIndexRoute: PengaturanIndexRoute,
  PresentasiIndexRoute: PresentasiIndexRoute,
  RaporIndexRoute: RaporIndexRoute,
  RubrikIndexRoute: RubrikIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
